<?php
// Configure this file for workflows on the current (local) server, to be stored
// adjacent to civicrm.settings.php
//
// FYI: top-level array keys are for developer information only; they are not
// used by the extension (civicrm_stepw_workflow.id is simple auto-increment).


// URLs must be complete with schema and FQDN; defining this variable makes it
// a little easier to type those in below, and to retain confguration across, e.g.
// developmen and live copies of a given site.
$ufBaseUrl = rtrim(CIVICRM_UF_BASEURL, '/');
return [
  '1' => [
    'settings' => [
      // Admin-facing title for this workflow.
      'title' => 'Example workflow',
      
      // Should the progress bar be displayed on the first step and count that step
      // in its "total step count"? For example: assume there are 5 steps:
      // If this is TRUE:
      //   - Step 1 will show a progress bar, and it will say "step 1 of 5"
      //   - Step 2 will show a progress bar, and it will say "step 2 of 5"
      //   - Remaining steps also show a progress bar with equivalent counting.
      // If this FALSE:
      //   - Step 1 will not show a progress bar
      //   - Step 2 will show a progress bar, and it will say "step 1 of 4"
      //   - Remaining steps also show a progress bar with equivalent counting.
      'progressOmitFirstStep' => FALSE,
      
      // A unique identifier. AlphanumericEventually this extension should auto-create such
      // an ID, but with this file-based config you must generate it yourself and
      // store it here. Suggested generation method from the command line using `cv`:
      // cv php:eval 'echo CRM_Stepw_Utils_General::generatePublicID()';
      'public_id' => 'd3778d9b27c29b52afe442ebce572bbcca23k',
    ],
    'steps' => [
      // TODO: when loading live data, ensure these are sorted in step order and keyed sequentially from 0.
      // At present, we assume this file is written with the steps in the correct order.
      
      // Item '0' is the first step in the workflow.
      [
        // options: Some steps may have various expressions based on whatever the user
        //   selected as "next" when completing the previous step. This config interplays
        //   with the 'optionLabels' config of the previous step (see below). Most steps will
        //   have only one value in 'options', and thus their preceding steps will have only one
        //   value in 'optionLabels'.
        //   
        //   In this example, we have a workflow which demonstrates this capability,
        //   with steps like these:
        //     Step 1: A WordPress page available at a given URL. At the bottom of this
        //       page, the user will see 2 "next" buttons (which are generated by this extension):
        //         - Video Option A (page)
        //         - Video Option B (page)
        //     Step 2: Because Step 1 offers two options, Step 2 has two expressions:
        //       - Video Option A (which is a CMS page with a given URL)
        //       - Video Option B (which is a CMS page with a given URL)
        //       Upon completion of Step 1, the user is expected to select on of those
        //       options, and they are then shown the appropriate page as Step 2.
        //       Note that in the configuration for Step 2, each options written
        //       to itself offer only one "next" button (in its "optionLabels" config).
        //       It /may/ be supported to offer multiple "optionLabels" in this
        //       situation, with the expectation that Step 3 will have multiple 
        //       options, but this has not been tested.)
        //     Step 3: Because each option in Step 2 offers only one "optionLabels"
        //       config, Step 3 is expected to have only one option, which it does.
        //       This option is an afform. The user is expected to fill in this
        //       form and submit it with the 'submit' button (the label of which
        //       is determined by the configurations in this step).
        //       
        //       NOTE ON AFFORM AND OPTIONS/OPTIONLABELS: When a displayed step
        //       option is type='afform', it cannot have multiple 'optionLabels',
        //       therefore, for any step having at last one option of type='afform',
        //       the subsequent step cannot have multiple 'options'.
        //       
        //     Step 4: Because the previous step offered an afform, this step has only
        //       one option (see NOTE ON AFFORM AND OPTIONS/OPTIONLABELS above).
        //       This option is type='afform', so it displays a second FormBuilder
        //       form, which the user will complete.
        //     Step 5: This step has one option, which is a CMS page with a given
        //       URL.  (Since this is the last step in the workflow, no "next"
        //       button will be displayed on this page.)
        //       
        //     
        //   As for this first step:
        //   As the first step, this page MUST have only one option, as logically
        //   there is no way to start with anything but a single expression of the first step 
        //   (i.e., How would a user even indicate that they wanted one or another option
        //   at this stage of the workflow? They cannot, so it must have only one option.)
        'options' => [
          [
            // What type of step is this? Options are:
            // - 'url': a CMS page on your site
            // - 'afform': A FormBuilder form.
            'type' => 'url',
            
            // What's the URL for this url-type step?
            'url' => $ufBaseUrl . '/prevention/welcome-workflow-1',
            
            // OptionLabels are the labels to display ON THIS OPTION/PAGE
            // for each of the options (in order) that are available in the
            // next step. This extension inserts 'next' buttons with the labels
            // given here. In this case, 2 'next' buttons will be displayed,
            // thus giving the user 2 options for what they'll do in the next step.
            'optionLabels' => [
              'Watch Video A',
              'Watch Video B',
            ],
          ],
        ],
      ],
      
      // Item '1', the second step in the workflow.
      [
        // Because the previous step had 2 values in its 'optionLabels' config,
        // this step is expected to offer 2 options. One of these will be displayed
        // based on the users's seclection (from the available 'optionLabels') in
        // the previous step.
        'options' => [
          // The first option is displayed if the user selects the first 'optionLabel'
          // in the previous step.
          [
            'type' => 'url',
            'url' => $ufBaseUrl . '/prevention/workflow-1-video-a/',
            'optionLabels' => [
              'Go to afform 1',
            ],
            
            // 'requireOnpageEnforcer': if true, assume that the displayed page
            // contains a Vimeo video, and attemp to ensure that the entire video
            // has played before allowing the user to proceed to the next step.
            'requireOnpageEnforcer' => 1,
          ],
          // The second option is displayed if the user selects the second 'optionLabel'
          // in the previous step.
          [
            'type' => 'url',
            'url' => $ufBaseUrl . '/prevention/workflow-1-video-b/',
            'requireOnpageEnforcer' => 1,
            'optionLabels' => [
              'Go to afform 1',
            ],
          ],
        ],
      ],
      // Item '2', the third step in the workflow.
      [
        'options' => [
          [
            'type' => 'afform',
            'afformName' => 'afformTESTFormStart',
            // Because this step has at least one afform option (this one),
            // the subsequent step MUST have only one option. (See NOTE ON AFFORM
            // AND OPTIONS/OPTIONLABELS, above.)
            'optionLabels' => [
              'Submit and Go to afform 2',
            ],
            'postSubmitValidation' => [
              // After the afform is fully submitted and processed, this extension
              // can perform validation to ensure that the submitted values conform
              // to some configured reqirememnt. Here we define that requirement.
              // This 'where' array will be passed to Api4 to ensure that the
              // contact defined in afform 'Individual1' meets the configured
              // criteria. If it does not, this user's workflow is ended with
              // display of a valudiation error (which is also configured within
              // this option, see below).
              'where' => [
                'Individual1' => [
                  ['age_years', '>=', 18],
                  ['age_years', '<=', 29],
                ],
                // Note that it's supported to define a similar array for Activity1
                // if the afform offerst that entity.
              ],
              // If criteria defined in 'where' are not met in this afform submission,
              // this 'failureMessage' will be displayed to the user. This config
              // value is raw HTML.
              'failureMessage' => '<p>You do not meet the requirements for this program.</p>',
            ],
          ],
        ],
      ],
      [
        'options' => [
          [
            'type' => 'afform',
            'afformName' => 'afformTestForm2Activity',
            'optionLabels' => [
              'Submit and view final step.',
            ],
          ],
        ],
      ],
      [
        'options' => [
          [
            'type' => 'url',
            'url' => $ufBaseUrl . '/example-final-page/',
            'optionLabels' => [
              // Because this option is in the final step, this extension will
              // not display a 'next' button. This config is written here only
              // as a place to record this notion; in a live config you could
              // simply leave this blank or omit it.
              'THIS SHOULD NOT DISPLAY',
            ],
          ],
        ],
      ],
    ],
  ],
];
